M48
; DRILL file {KiCad 9.0.1} date 2025-09-14T18:57:01-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-14T18:57:01-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.850
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X131.705Y-124.0
X152.205Y-124.0
T2
X143.735Y-143.0
X146.275Y-143.0
M30
